### ISSUE TITLE
Cange requests

### ISSUE THREAD

**Issue by zankevich** [eugenek0110/nebular#1]
Thank you for adding me! @eugenek0110 

Here I have some requirements adjustments:
1. Form must be responsive as on provided screenshot. At least three breakpoints (mobile, tablet, desktop).
2. Validations must be added: (you can use `date-fns` for date comparison)
- required for `depart date` and `return date`
- `depart date` and `return date` can't be in the past
- `return date` must be same date as `depart date` or greater
- when you click on `search` button it must show validation errors (if any)
- it must display validation error under the input (if any) and display error semantic color as an input border
- user must be able to select only valid values from date pickers
- user must be able to enter date manually from keyboard (`mm/dd/yyyy`)

Bonus points for adding unit tests.
Bonus point for mocking request (`?dateFrom=&dateTo=`) and displaying data under the search form. You can use simple table or `Tree Grid` component from Nebular. It just fine to mock as `of([arrayOfData])` using angular HTTP client.

**Comment by eugenek0110** [comment]
required for depart date and return date - required class validator is used
depart date and return date can't be in the past - ok, we can use min tag for both dates... or it must be done by custom validation?
return date must be same date as depart date or greater - ok
user must be able to select only valid values from date pickers - hm... so we can just use attribute min - but second and third clauses of conditions will be ignored. I mean that they will be ignored by validation. Cause it impossible to select them using min attribute... ah we can simply use input field...
